export default {
    DEFAULT_BLACK: '#000000',
    DEFAULT_RED: '#ff0000',
    DEFAULT_PRIMARY: '#0D6EFD',
    DEFAULT_SECONDARY: '#6C757D',
    DEFAULT_SUCCESS: '#008000',
    DEFAULT_WARNING: '#FFC107',
    DEFAULT_ORANGE: '#D86C27',
    DEFAULT_WHITE: '#FFFFFF',
    DEFAULT_GRAY: '#A3A3A3',
    DEFAULT_GREY: '#EEEEEE',
};